package com.sparepartmanagementsystem.inventory;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;

/**
 * DESIGN PATTERN: Factory Pattern (Creational Pattern)
 * Encapsulates the logic to create formatted audit reports based on report type.
 */
public class InventoryReportFactory {

    private static final DateTimeFormatter FORMATTER = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");

    // Factory method to produce formatted audit report content based on report type
    public static String createReportContent(String reportType, List<InventoryItem> items,
                                            int maxCapacity, int rackCapacity,
                                            String fromDate, String toDate, String notes) {
        int totalStock = items.stream().mapToInt(InventoryItem::getQuantity).sum();
        double totalValuation = items.stream().mapToDouble(InventoryItem::calculateValuation).sum();
        long lowStockCount = items.stream().filter(InventoryItem::isLowStock).count();
        int capacityPct = maxCapacity > 0 ? (int) Math.round(((double) totalStock / maxCapacity) * 100) : 0;

        StringBuilder sb = new StringBuilder();
        sb.append(String.format("Report Type: %s\n", reportType));
        sb.append(String.format("Generated Date: %s\n", LocalDateTime.now().format(FORMATTER)));
        sb.append(String.format("Period Range: %s to %s\n",
                (fromDate != null && !fromDate.isBlank() ? fromDate : "All Records"),
                (toDate != null && !toDate.isBlank() ? toDate : "Current")));
        sb.append("Generated By: Inventory Admin (Depot Central)\n");
        if (notes != null && !notes.isBlank()) {
            sb.append(String.format("Manager Notes: %s\n", notes.trim()));
        }
        sb.append("\nEXECUTIVE SUMMARY METRICS\n");
        sb.append(String.format("• Total Part SKUs Cataloged: %d\n", items.size()));
        sb.append(String.format("• Total Physical Units: %d / %d Max (%d%% Occupied)\n", totalStock, maxCapacity, capacityPct));
        sb.append(String.format("• Available Free Space: %d Units\n", Math.max(0, maxCapacity - totalStock)));
        sb.append(String.format("• Total Stock Valuation: Rs. %,.2f\n", totalValuation));
        sb.append(String.format("• Critical Low Stock SKUs: %d\n\n", lowStockCount));

        String typeLower = (reportType != null) ? reportType.toLowerCase() : "";

        if (typeLower.contains("low stock") || typeLower.contains("safety threshold")) {
            sb.append("CRITICAL LOW STOCK AUDIT BREAKDOWN\n");
            for (InventoryItem i : items) {
                if (i.isLowStock()) {
                    String status = i.getQuantity() == 0 ? "OUT OF STOCK" : "LOW STOCK";
                    sb.append(String.format("• %s [%s] — Stock: %d (Reorder: %d) — Rs. %,.2f — %s\n",
                            i.getPartName(), i.getPartId(), i.getQuantity(), i.getReorderLevel(), i.getUnitPrice(), status));
                }
            }
        } else if (typeLower.contains("capacity") || typeLower.contains("rack") || typeLower.contains("utilization")) {
            int rackA = 0, rackB = 0, rackC = 0, rackD = 0;
            for (InventoryItem i : items) {
                String loc = i.getStorageLocation().toUpperCase();
                if (loc.contains("RACK A") || loc.equals("A")) rackA += i.getQuantity();
                else if (loc.contains("RACK B") || loc.equals("B")) rackB += i.getQuantity();
                else if (loc.contains("RACK C") || loc.equals("C")) rackC += i.getQuantity();
                else if (loc.contains("RACK D") || loc.equals("D")) rackD += i.getQuantity();
                else rackA += i.getQuantity();
            }
            sb.append("WAREHOUSE STORAGE CAPACITY & RACK BREAKDOWN\n");
            sb.append(String.format("• Total Storage Limit: %d Units across 4 Racks\n", maxCapacity));
            sb.append(String.format("• Rack Capacity Limit: %d Units per Rack\n", rackCapacity));
            sb.append(String.format("• Rack A: %d / %d Units (%d%%)\n", rackA, rackCapacity, (int) Math.round(((double) rackA / rackCapacity) * 100)));
            sb.append(String.format("• Rack B: %d / %d Units (%d%%)\n", rackB, rackCapacity, (int) Math.round(((double) rackB / rackCapacity) * 100)));
            sb.append(String.format("• Rack C: %d / %d Units (%d%%)\n", rackC, rackCapacity, (int) Math.round(((double) rackC / rackCapacity) * 100)));
            sb.append(String.format("• Rack D: %d / %d Units (%d%%)\n\n", rackD, rackCapacity, (int) Math.round(((double) rackD / rackCapacity) * 100)));
            sb.append("RACK ALLOCATION BY PART\n");
            for (InventoryItem i : items) {
                sb.append(String.format("• %s [%s] — %s: %d units\n", i.getPartName(), i.getPartId(), i.getStorageLocation(), i.getQuantity()));
            }
        } else {
            sb.append("CURRENT WAREHOUSE REPOSITORY CATALOG\n");
            for (InventoryItem i : items) {
                double val = i.calculateValuation();
                sb.append(String.format("• %s [%s] — %s — %d units — Rs. %,.2f (Valuation: Rs. %,.2f)\n",
                        i.getPartName(), i.getPartId(), i.getStorageLocation(), i.getQuantity(), i.getUnitPrice(), val));
            }
        }
        sb.append("\nAUDIT SUMMARY\nOfficial warehouse repository audit certified for management review.\n");
        return sb.toString();
    }
}
