spring.application.name=SparePartSystem

# JSP Configurations
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

# Microsoft SQL Server Configurations (Port 1433 Direct)
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=spare_parts_db;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=chanithu123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.sql.init.mode=always

# Embedded Tomcat & JSP Live Reload Settings
server.tomcat.jsp.development=true
server.error.include-message=always
server.error.include-stacktrace=always
server.error.include-exception=true